
spine:
  defaults:
    platform: cEOS-lab
    bgp_as: 65001
    loopback_ipv4_pool: 192.168.101.0/24
    mlag: false
  nodes:
    - name: spine1
      id: 11
      evpn_route_servers: [spine3, spine4]
    - name: spine2
      id: 12
      evpn_route_servers: [spine3, spine4]

l3leaf:
  defaults:
    bgp_as: 65101-65180
    platform: cEOS-lab
    loopback_ipv4_pool: 192.168.101.0/24
    vtep_loopback_ipv4_pool: 192.168.102.0/24
    uplink_interfaces: [Ethernet3, Ethernet4]
    uplink_switches:  [spine1, spine2]
    uplink_ipv4_pool: 192.168.103.0/24
    mlag_interfaces: [Ethernet1, Ethernet2]
    mlag_peer_ipv4_pool: 10.255.255.0/24
    mlag_peer_l3_ipv4_pool: 10.255.254.0/24
    virtual_router_mac_address: 00:1C:73:00:00:99
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
    mlag: true
  nodes:
    - name: borderleaf1
      id: 3
      uplink_switch_interfaces: [Ethernet7, Ethernet7]
  node_groups:
    - group: mlag12
      nodes:
        - name: leaf1
          id: 1
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        - name: leaf2
          id: 2
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
