
spine:
  defaults:
    platform: cEOS-lab
    bgp_as: 65002
    loopback_ipv4_pool: 192.168.201.0/24
    mlag: false
  nodes:
    - name: spine3
      id: 13
      evpn_route_servers: [spine1, spine2]
    - name: spine4
      id: 14
      evpn_route_servers: [spine1, spine2]

l3leaf:
  defaults:
    bgp_as: 65201-65280
    platform: cEOS-lab
    loopback_ipv4_pool: 192.168.201.0/24
    vtep_loopback_ipv4_pool: 192.168.202.0/24
    uplink_interfaces: [Ethernet5, Ethernet6]
    uplink_switches:  [spine3, spine4]
    uplink_ipv4_pool: 192.168.03.0/24
    mlag_interfaces: [Ethernet1, Ethernet2]
    mlag_peer_ipv4_pool: 10.255.255.0/24
    mlag_peer_l3_ipv4_pool: 10.255.254.0/24
    virtual_router_mac_address: 00:1C:73:00:00:99
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
    mlag: true
  nodes:
    - name: borderleaf2
      id: 3
      uplink_switch_interfaces: [Ethernet8, Ethernet8]
  node_groups:
    - group: mlag34
      bgp_as: 65199
      nodes:
        - name: leaf3
          id: 1
          uplink_switch_interfaces: [Ethernet5, Ethernet5]
        - name: leaf4
          id: 2
          uplink_switch_interfaces: [Ethernet6, Ethernet6]
